### PR TITLE
Create 2017-12-28-My Experience In GCI 2017

### PR DESCRIPTION
**Pull request by ChiMugdha**
Hello,
This is a pull request for a blog. The blog post I wrote about my experience in GCI 2017 is attached as a link below.

https://github.com/jboss-outreach/blog.jboss-outreach.org/compare/master...ChiMugdha:patch-1#diff-2e4687e6cf1912e162fd8ca3aaadd1f6

### CODE REVIEW

**Comment by anshumanv** [comment]
Please move your file to `/_posts`

**Comment by ChiMugdha** [comment]
Hi,
How do I move this file to /_posts ?

**Comment by anshumanv** [comment]
Create file in [this](https://github.com/jboss-outreach/blog.jboss-outreach.org/tree/master/_posts) directory.
The one that you have uploaded to the repo root.

**Comment by ChiMugdha** [comment]
It says I don't have write access...it won't allow me to propose a new file.

**Comment by anshumanv** [comment]
You don't have access to write to upstream, make changes in your fork and those will be reflected here, try adding here - https://github.com/ChiMugdha/blog.jboss-outreach.org/tree/master/_posts

**Comment by ChiMugdha** [comment]
Ok...it asks me to either "Commit directly to the master branch." or "Create a new branch for this commit and start a pull request." Which one do I choose?

**Comment by anshumanv** [comment]
You've sent this PR from `patch-1` branch, please make changes in that branch to reflect changes in this PR.

**Comment by ChiMugdha** [comment]
Thank you so much!

**Pull request closed without merging**
