### PR TITLE
My GCI submission blog post

### PR DESCRIPTION
**Pull request by Ashesh3**
My GCI submission blog post :D

### CODE REVIEW

**Comment by neelanshsahai** [comment]
Also creating multiple Pull Request for the same purpose is not how it works. Updating the same branch and Pushing is the preferred way rather than closing the PR and deleting the fork :wink:

**Comment by Ashesh3** [comment]
@neelanshsahai Thank you! I fixed the post.. hopefully its good now. and thanks for the tip! I am still learning :D Let me know if i need to do anything else

**Comment by neelanshsahai** [comment]
Just one last thing...
Squash your commits (One commit per PR) :sunglasses: 
Everything else **LGTM** :+1:

**Comment by Ashesh3** [comment]
@KeenWarrior Updated! and i squashed the commits

**Pull request merged**
